[package]
name = "getting_started_step_1_sqlite"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Taryn Hill <taryn@phrohdoh.com>"]
edition.workspace = true
publish = false

[dependencies]
diesel = { version = "2.2.0", path = "../../../diesel", features = ["sqlite"] }
dotenvy = "0.15"
libsqlite3-sys = { workspace = true, features = ["bundled"] }

[dev-dependencies]
assert_cmd = "2.0.14"
tempfile = "3"
diesel_migrations = { version = "2.2.0", path = "../../../diesel_migrations" }

[[bin]]
name = "show_posts_step_1"
path = "src/bin/show_posts.rs"
doc = false

[lib]
doc = false
